before_install <- function(){
    ## Build various bits of autogenerated code
    install.packages(c("devtools", "roxygen2", "testthat", "rmarkdown"))
    devtools::install_deps(dependencies=c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances"),
                           quiet=FALSE, upgrade=TRUE)
    roxygen2::roxygenize()
    Rcpp::compileAttributes(verbose=TRUE)
    devtools::document()

    ## GitHash as used by PKG:::PKG_git_hash()
    writeLines(system("git rev-parse HEAD", intern=TRUE), "inst/GIT.HASH")

    ## Write custom dictionary words
    saveRDS(c("ArXiv"), ".aspell/simplecolors.rds")
}

after_success <- function(){
    devtools::install()
    rmarkdown::render("README.Rmd")
    unlink(Sys.glob("PKG.Rcheck"), recursive=TRUE, force=TRUE)
    unlink(Sys.glob("PKG*.tar.gz"), recursive=TRUE, force=TRUE)
    file.rename(".gitignore.deploy", ".gitignore")
    unlink(Sys.glob("src/*o"), force=TRUE)
}
